language: node_js
node_js:
  - "13"

os: linux

env:
  - BASE_URL=http://localhost:3000
  - MONGO_DB_URL=mongodb://127.0.0.1:27017/apiapi

cache:
  npm: true
  directories:
    - "node_modules"
    - ~/.cache

branches:
  only:
    - "master"
    - "develop"

install:
  - "npm install"


before_script:
  - "npm run lint"

script:
  - "npm run build"

